### ISSUE TITLE
Syntax of pasted e-mails

### ISSUE THREAD

**Issue by spajk-cz** [qauff/hibp-breach-lister-cli#3]
Hi, first at all, i like the idea of your project. But i stack in the start - when i paste few e-mail addresses and save the file index.js, after run command i get an error:

_---- Output after run a command ----_

node index.js > output.json                                                                                                                         1 ⨯
/home/spajk/Tools/hibp-breach-lister-cli/index.js:5
admin@xxxxxx.cz
     ^

SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

----
Is there a specific format of e-mail addresses? I tried ", ' but thats has no effect.

**Comment by englut** [comment]
Hey @spajk-cz, that's just a JavaScript array, so you'd format it like this:

```
const emails = [
    'user1@example.com',
    'user2@example.com',
    'user3@example.com',
    'user4@example.com'
]
```

This tool was slapped together reaaally quickly. And hasn't been maintained, so hopefully it works for ya!

**Comment by spajk-cz** [comment]
Thanks for fast reply @qauff ! It works, but i get the 401 reply in all tested addresses :( 

{"email":"admin@xxx.cz","breaches":401}

I must enter API key somewhere, correct? :)

**Comment by englut** [comment]
Ahhh it looks like they've changed the API, which requires an API Key via a paid subscription. This tool will need to be re-written for the new API and use an API key. I think I will just archive this for now as I don't have time to refactor :)

**Comment by englut** [comment]
@spajk-cz I've re-written the tool to support v3 API using rust; and also relocated the codebase.

If you're still interested or need it, you can find the re-written tool [here](https://sr.ht/~quaff/hibp-breach-lister-cli)!
